config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: 'items#index'

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :cards

  resources :items do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    member do
      get "change0", to: 'items#change0'
      get "change1", to: 'items#change1'
    end
  end
  
  resources :users do
    member do
      get "profile"
      get "logout"
      get "info"
      get "pageedit"
    end
  end

  get '/registration', to: 'items#registration'
  get '/card', to: 'items#card'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :comments ,dependent: :destroy
  has_many :images ,dependent: :destroy
  belongs_to :user,optional: true
  has_one :order
  belongs_to_active_hash :prefecture
  accepts_nested_attributes_for :images

  validates :name, :text, :condition, :fee_burden, :service, :prefecture_id, :handing_time, :price, presence: true
  #画像がない場合のバリデーション
  validate :require_any_image
  def require_any_image
    errors.add(:base, :no_image) if images.blank?
  end

  enum condition: {'新品未使用': 1, '未使用に近い': 2, '目立った傷や汚れなし': 3, '傷や汚れあり': 4, '全体的に状態が悪い': 5}
  enum fee_burden: {'送料込み（出品者負担）': 1, '着払い（購入者負担）': 2}
  enum service: {'未定': 1, 'らくらくメルカリ便': 2, 'ゆうメール': 3, 'レターパック': 4, '普通郵便（定形、定形外）': 5, 'クロネコヤマト': 6, 'ゆうパック': 7, 'クリックポスト': 8, 'ゆうパケット': 9}
  enum handing_time: {'１〜２日で発送': 1, '２〜３日で発送': 2, '４〜７日で発送': 3}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  before_action :set_user 

  def index
    @items = Item.all.where.not(trading_status: 2)
  end
  
  def new
    @item = Item.new
    @item.images.build
    render layout: 'devise'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.build
      redirect_to new_item_path
    end
  end
  
  def show
    @user = User.find(@item[:seller_user_id])
    @items = Item.where(seller_user_id: @user[:id]).where.not(id: params[:id]).where.not(trading_status: 2)
    @images = @item.images
    render layout: 'items_show'
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render item_path
    end
  end

  def edit
    render layout: 'devise'
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path(@item)
    end
  end

  def change0
    @item = Item.find(params[:id])
    @item.update_attribute(:trading_status, "0")
    redirect_to item_path
  end

  def change1
    @item = Item.find(params[:id])
    @item.update_attribute(:trading_status, "1")
    redirect_to item_path
  end

  private
  def item_params
    params.require(:item).permit(:name,:text,:condition,:fee_burden,:service,:prefecture_id,:handing_time,:price,:trading_status,:service,:category_id, 
    images_attributes:[:image_url, :_destroy, :id]).merge(seller_user_id:current_user.id)
  end

  # def image_params
    #imageのストロングパラメータの設定.js側でimagesをrequireすれば画像のみを引き出せるように設定する。
    # params.require(:images).permit({:images => []})
  # end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_user
    @user = User.where(id: current_user.id).first if user_signed_in?
  end

end

app/views/items/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['users', 'show']
  - breadcrumb :user_show

- when ['user_chat_rooms', 'index']
  - breadcrumb :user_chat_rooms_index

= breadcrumbs separator: " &nbsp;&nbsp;&#62;&nbsp; "

app/views/items/_btn.html.haml
.sellbtn
  - if user_signed_in?
    = link_to new_item_path do
      .sellbtn__name
        出品
      %i.fas.fa-camera.fa-3x
  - else 
    = link_to new_user_session_path do
      .sellbtn__name
        出品
      %i.fas.fa-camera.fa-3x

app/views/items/_footer.html.haml
.footerWrapper
  .footer
    .footer__upper
      .footer__upper_1
        .footer__upper__1__list
          %ul
            %li.footer__upper__1__list__title エフマケについて
            %li
              = link_to "会社概要","#"
            %li
              = link_to "採用情報","#"
            %li
              = link_to "プレスリリース","#"
            %li
              = link_to "公式ブログ","#"
            %li
              = link_to "エフマケロゴ利用ガイドライン","#"
        .footer__upper__1__icons
          %i.fab.fa-twitter
          %i.fab.fa-facebook-square
      .footer__upper__2
        %ul
          %li.footer__upper__1__list__title ヘルプ&amp;ガイド
          %li
            = link_to "エフマケガイド","#"
          %li
            = link_to "らくらくエフマケ便","#"
          %li
            = link_to "ゆうゆうエフマケ便","#"
          %li
            = link_to "大型エフマケ便","#"
          %li
            = link_to "車体取引ガイド","#"
          %li
            = link_to "エフマケあんしん・あんぜん宣言！","#"
          %li
            = link_to "偽ブランド品撲滅への取り組み","#"
          %li
            = link_to "エフマケボックス","#"
      .footer__upper__3
        .footer__upper__1__list__title プライバシーと利用規約
        .footer__upper__3__box
          .footer__upper__3__box__left
            %ul
              %li
                = link_to "プライバシーポリシー","#"
              %li
                = link_to "エフマケ利用規約","#"
              %li
                = link_to "あんしんスマホサポート制度に関する利用規約","#"
              %li
                = link_to "コンプライアンスポリシー","#"
          .footer__upper__3__box__right
            %ul
              %li
                = link_to "個人データの安全管理に係る基本方針","#"
              %li
                = link_to "特定商取引に関する表記","#"
              %li
                = link_to "資金決済法に基づく表示","#"
              %li
                = link_to "法令遵守と犯罪防止のために","#"
      .footer__upper__4
        %ul
          %li.footer__upper__1__list__title 国
          %li
            = link_to "日本","#"
          %li
            = link_to "United States","#"
    .footer__bottom
      .footer__bottom__logo
        = link_to image_tag("/fmarket_logo_red.svg", size: "124x34"), root_path
      .footer__bottom__copy.footer
        %p © Fmake, Inc.
      .footer__bottom__null

app/views/items/_header.html.haml
.headWrapper
  .header
    .header__upperBox
      .header__upperBox__logo
        = link_to image_tag("/fmarket_logo_red.svg", size: "134x36"), root_path
      .header__upperBox__search
        %form.header__upperBox__search
          %input.header__upperBox__search__form{placeholder: "何かお探しですか？", type: "text"}/
    .header__bottomBox
      .header__bottomBox__left
        .header__bottomBox__left__category
          = link_to "/" do
            %i.fas.fa-list-ul
            全ての商品一覧
        .header__bottomBox__left__brand
      .header__bottomBox__right
        %ul.header__bottomBox__right__nav
          - if user_signed_in?
            %li.header__bottomBox__right__nav__list.good
              = link_to 'いいね！一覧', "/"
            %li.header__bottomBox__right__nav__list.info
              = link_to 'お知らせ', "#"
            %li.header__bottomBox__right__nav__list.todo
              = link_to 'やることリスト', "#"
            %li.header__bottomBox__right__nav__list
              = link_to 'マイページ', user_path(current_user)
          - else
            %li.header__bottomBox__right__nav__list
              = link_to "新規会員登録", new_user_registration_path, class: "nav_btn_red"
            %li.header__bottomBox__right__nav__list
              = link_to "ログイン", new_user_session_path, class: "nav_btn_blue"

app/views/items/_myside.html.haml
.sidebar
  .sidebar__mypage
    %ul.sidebar__mypage__nav
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          マイページ
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          お知らせ
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          やることリスト
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          いいね！一覧
          %i.fas.fa-chevron-right
      %li
        = link_to new_item_path, class: "sidebar__mypage__nav__item" do
          出品する
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          ニュース一覧
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          評価一覧
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          ガイド
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          お問い合わせ
          %i.fas.fa-chevron-right
    %h3.sidebar__mypage__head えふぺい
    %ul.sidebar__mypage__nav
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          売上・振込申請
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          ポイント
          %i.fas.fa-chevron-right
    %h3.sidebar__mypage__head 設定
    %ul.sidebar__mypage__nav
      %li
        = link_to pageedit_user_path(current_user), class: "sidebar__mypage__nav__item" do
          プロフィール
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      %li
        = link_to cards_path, class: "sidebar__mypage__nav__item" do
          支払い方法
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          メール/パスワード
          %i.fas.fa-chevron-right
      %li
        = link_to info_user_path(current_user), class: "sidebar__mypage__nav__item" do
          本人情報
          %i.fas.fa-chevron-right
      %li
        = link_to "#", class: "sidebar__mypage__nav__item" do
          電話番号の確認
          %i.fas.fa-chevron-right
      %li
        = link_to logout_user_path(current_user), class: "sidebar__mypage__nav__item" do
          ログアウト
          %i.fas.fa-chevron-right

app/views/items/edit.html.haml
=form_for @item do |f|
  .edit
    .edit__header
      = link_to root_path do
        = image_tag "/fmarket_logo_red.svg", size: "185x49", class: "single_header__img"
    .edit__main
      .edit__main__box
        .edit__main__box__title
          商品情報の入力
        .sell__main__box__upload
          .edit__main__box__upload__header
            出品画像
            %span#span 必須
            %p{id:"p"} 最大10枚までアップロードできます
          .sell__main__box__upload__box
            = f.fields_for :images do |i|
              .sell__main__box__upload__box__preview.clearfix
                %li.sell__main__box__upload__items
                  %figure.sell__main__box__upload__items__figure
                    = i.label :image, class: "image" do
                      #img_field{:onclick => "$('#file').click()"}
                        = image_tag i.object.image_url.url, id: "edit_img"
                      = i.file_field :image_url, class: "image",  id: "file", style: "display:none"
          .sell__main__box__upload__box
            .sell__main__box__upload__box__preview.clearfix
              %label{id:"box__drop"}
                .sell__main__box__upload__box__preview__guide-0{id:"guide_box"}
                  %pre#pc
                    %i.fas.fa-camera.fa-lg
                    = preserve "<br>ドラッグアンドドロップ<br>またはクリックしてファイルをアップロード"
                    =f.fields_for :images,html: {id:'new_item'} do |i|
                      =i.file_field :image_url,id:"image_editer",style:"display:none"
        .edit__main__box__form 
          .edit__main__box__form__group
            商品名
            %span#span 必須
            = f.text_field :name,class:"edit__main__box__form__group__1",placeholder:"商品名(必須４０文字まで)"
          .edit__main__box__form__group
            商品の説明
            %span#span 必須
            = f.text_area :text,class:"edit__main__box__form__group__1",placeholder:"商品の説明(必須1000文字以内)"
          .edit__main__box__status__box__group
            商品の状態
            %span#span 必須
            = f.select :condition, Item.conditions.keys, prompt: "--"
        .edit__main__box__status
          配送について
          .edit__main__box__status__box
            .edit__main__box__status__box__group
              配送料の負担
              %span#span 必須
              = f.select :fee_burden, Item.fee_burdens.keys, prompt: "--"
            .edit__main__box__status__box__group
              配送方法
              %span#span 必須
              =f.select :service,Item.services.keys,prompt: "--"
            .edit__main__box__status__box__group
              発送元地域
              %span#span 必須
              =f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--"
            .edit__main__box__status__box__group
              発送までの日数
              %span#span 必須
              =f.select :handing_time,Item.handing_times.keys,prompt: "--"
        .edit__main__box__price
          販売価格(300~9.999,999)
          %span
          = link_to '?', '#',class:"edit__main__box__price__atag"
          .edit__main__box__price__box
            .edit__main__box__price__box__group
              .edit__main__box__price__box__group__left
                価格
                %span#span 必須
              .edit__main__box__price__box__group__right
                ¥
                = f.text_field :price, class:"edit__main__box__price__box__group__right__1",placeholder:"例) 300"
            .edit__main__box__price__box__tax
              販売手数料(10%)
              .edit__main__box__price__box__tax__1

              .edit__main__box__price__box__profit
                販売利益
              .edit__main__box__price__box__profit__1
              -#= f.text_field :price,style:"display:none",id:"price"
        .edit__main__box__under
          %button.btn{type:"submit",class:"edit__main__box__under__btn"} 変更する
          %button.btn{type:"submit",class:"edit__main__box__under__btn1"} キャンセル
    .edit__main__footer
      .edit__main__footer__box
        %ul#ul
          = link_to "プライバシーポリシー","#",class:"edit__main__footer__box__atag"
          = link_to "エフマケ利用規約","#",class:"edit__main__footer__box__atag"
          = link_to "特定商取引に関する表記","#",class:"edit__main__footer__box__atag"
        = link_to "#", id: "atag" do
          = image_tag "/fmarket_logo_red.svg", size: "185x49", class: "sell__main__footer__box__atag__img"
        %p#p © Fmake, Inc.

app/views/items/index.html.haml
.index
  .index__box
    .slider
      %ul.slider__box
        %li
          .slick_1
            = image_tag "/F-Market1.png", size: "640x390", class: "slick_img"
        %li
          .slick_2
            = image_tag "/F-Market2.png", size: "1040x390", class: "slick_img"
    .category
      %h2 人気のカテゴリー
      .category__type
        %ul
          %li メンズ
          %li レディース
          %li 家電・スマホ・カメラ
          %li おもちゃ・ボビーグッズ
    .list
      .list__title
        %h3 商品一覧
        = link_to 'もっと見る', "#"
      .items
        %ul
          - @items.each do|item|
            %li.item
              = link_to item_path(item) do
                %figure#figure1
                  - item.images.each do |image|
                    =image_tag "#{image.image_url}", alt: "商品の写真", class:"picture"
                  %span#price="¥#{item.price}"
                  .pic
                  %figcaption.exp
                    %span=item.name

app/views/items/login_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FMarketF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/aacf386ed8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="session_wrapper">
      <div class="single_container">
        <div class="single_header">
          <a href="/"><img class="single_header__img" src="fmarket_logo_red.svg" width="185" height="49"></a>
        </div>
        <div class="session__main">
          <div class="session__main__container">
            <h2 class="session__main__container__title">新規会員登録</h2>
            <div class="session__main__container__box">
              <%= link_to new_user_registration_path, class: "btn_default btn_mail" do %>
                <i class="far fa-envelope icon_mail"></i>メールアドレスで登録する
              <% end %>
              <%= link_to new_user_registration_path, class: "btn_default btn_facebook" do %>
                <i class="fab fa-facebook-square icon_facebook"></i>Facebookで登録する
              <% end %>
              <%= link_to new_user_registration_path, class: "btn_default btn_google" do %>
                <i class="fab fa-google icon_google"></i>Googleで登録する
              <% end %>
            </div>
          </div>
        </div>
        <footer class="single__footer">
          <nav>
            <ul>
              <li><a href="#">プライバシーポリシー</a></li>
              <li><a href="#">メルカリ利用規約</a></li>
              <li><a href="#">特定商取引に関する表記</a></li>
            </ul>
          </nav>
          <a href="/"><img class="single__footer__img" src="logo_gray.svg" width="80px" height="65px"></a>
          <p>&copy; team.F</p>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/items/login_page.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FMarketF
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :src => "https://kit.fontawesome.com/aacf386ed8.js"}
  %body
    .session_wrapper
      .single_container.nomargin
        .single_header
          %a{:href => "/"}
            %img.single_header__img{:height => "49", :src => "fmarket_logo_red.svg", :width => "185"}/
        .session__main
          .session__main__container
            .session__main__container__regist
              %p アカウントをお持ちでない方はこちら
              = link_to registration_page_path, class: "btn_regist" do
                新規会員登録
            .session__main__container__box
              = link_to new_user_registration_path, class: "btn_default btn_facebook" do
                %i.fab.fa-facebook-square.icon_facebook>
                Facebookでログイン
              = link_to new_user_registration_path, class: "btn_default btn_google" do
                %i.fab.fa-google.icon_google>
                Googleでログイン
            %form.login__form
              %input.form_text{:placeholder => "メールアドレス", :type => "text"}/
              %input.form_text{:placeholder => "パスワード", :type => "text"}/
            .session__main__container__btn
              = link_to root_path, class: "btn_login" do
                ログイン
              %a.forget_password{:href => "#"} パスワードをお忘れの方はこちら
        %footer.single__footer
          %nav
            %ul
              %li
                %a{:href => "#"} プライバシーポリシー
              %li
                %a{:href => "#"} メルカリ利用規約
              %li
                %a{:href => "#"} 特定商取引に関する表記
          %a{:href => "/"}
            %img.single__footer__img{:height => "65px", :src => "logo_gray.svg", :width => "80px"}/
          %p © team.F

app/views/items/mypage.html.haml
- breadcrumb :mypage
.bread
  .bread__name
    = breadcrumbs 
.mypage
  .mypage__container
    .mypage__container__side
      = render partial: 'myside'
    .mypage__container__list
      .mypage__container__list__top
        .mypage__container__list__top__header
          .mypage__container__list__top__header__icon
            = render partial: 'items/mypage/icon'

        .mypage__container__list__top__body
          %ul.mypage_tab.top_tab
            %li.select お知らせ
            %li やることリスト
          %ul.top_content
            %li
              =render partial: 'items/mypage/news'
              .list__btn
                = link_to "#" do
                  .list__btn__text
                    一覧を見る
            %li.hide
              = render partial: 'items/mypage/todo'

      .mypage__container__list__under
        .mypage__container__list__under__header
          購入した商品
        .mypage__container__list__under__body
          %ul.mypage_tab.under_tab
            %li.select 取引中
            %li 過去の取引
          %ul.under_content
            %li
              =render partial: 'items/mypage/trading'
            %li.hide
              = render partial: 'items/mypage/transaction'

app/views/items/registration_page.html.haml
%body
  .session_wrapper
    .single_container
      .single_header
        = link_to '', "#"
        = image_tag "/fmarket_logo_red.svg", size: "185x49", class: "single_header__img"
      .session__main
        .session__main__container
          %h2.session__main__container__title 新規会員登録
          .session__main__container__box
            = link_to step1_signup_index_path, class: "btn_default btn_mail" do
              %i.far.fa-envelope.icon_mail
              メールアドレスで登録する
            = link_to new_user_registration_path, class: "btn_default btn_facebook" do
              %i.fab.fa-facebook-square.icon_facebook
              Facebookで登録する
            = link_to new_user_registration_path, class: "btn_default btn_google" do
              %i.fab.fa-google.icon_google
              Googleで登録する
      %footer.single__footer
        %nav
          %ul
            %li
              = link_to 'プライバシーポリシー', "#"
            %li
              = link_to 'メルカリ利用規約', "#"
            %li
              = link_to '特定商取引に関する表記', "#"
        = link_to '', "/"
        = image_tag "/logo_gray.svg", size: "80x65", class: "single__footer__img"
        %p © team.F

app/views/items/show.html.haml
- breadcrumb :item
.bread
  .bread__name
    = breadcrumbs

.item-details-body
  .item-details
    %h1.item-details__name
      = @item.name
    .item-details__content
      .item-details__content__left
        %ul.item-details__content__left__main
          - @images.each do |image|
            %li.item-details__content__left__main__image
              %figure#top_img
                = image_tag "#{image.image_url}", size: "300x300"
                -if @item.trading_status === 0
                  = image_tag "/F-Market3.png", size: "150x150", class: "pause_img"

        %ul.item-details__content__left__list
          - @images.each do |image|
            %li.item-details__content__left__list__image
              %figure#list_img
                = image_tag "#{image.image_url}", size: "60x60"

      %table.item-details__content__right
        %tbody
          %tr
            %th 出品者
            %td
              = link_to '#', class: "item-seller__name" do
                = @user.nickname
              .item-seller__ratings
                .item-seller__ratings__box
                  = icon 'fas', 'laugh', class: 'item-seller__ratings__icon--laugh facial__expression2'
                  %span 0
                .item-seller__ratings__box
                  = icon 'fas', 'meh', class: 'item-seller__ratings__icon--meh facial__expression2'
                  %span 0
                .item-seller__ratings__box
                  = icon 'fas', 'frown', class: 'item-seller__ratings__icon--frown facial__expression2'
                  %span 0
          %tr
            %th カテゴリー
            %td
              = link_to '#', class: 'item-details__category' do
                メンズ
          %tr
            %th ブランド
            %td
              = link_to '#', class: 'item-details__brand' do
                = @item.brand
          %tr
            %th 商品のサイズ
            %td M
          %tr
            %th 商品の状態
            %td 
              = @item.condition
          %tr
            %th 配送料の負担
            %td 
              = @item. fee_burden
          %tr
            %th 配送の方法
            %td 
              = @item.service
          %tr
            %th 配送元地域
            %td
              = link_to '#', class: 'item-details__area' do
                = @item.prefecture.name
          %tr
            %th 発送日の目安
            %td 
              = @item.handing_time

    .item-details__price-box
      %span.item-details__price-box--price
        = converting_to_jpy(@item.price)
      %span.item-details__price-box--tax (税込)
      %span.item-details__price-box--shipping-fee 送料込み

    -if user_signed_in? && current_user.id == @item.seller_user_id
      = link_to edit_item_path(@item), class: "item-details__buy-btn" do
        この商品を編集する
      -if @item.trading_status == 1
        = link_to change0_item_path(@item), action: :change0, method: :get, class: "item-details__buy-btn" do
          出品を一旦停止する
      -elsif @item.trading_status == 0
        = link_to change1_item_path(@item), class: "item-details__buy-btn" do
          出品を再開する
      = link_to item_path(@item), method: :delete, class: "item-details__buy-btn" do
        この商品を削除する

    -elsif @item.trading_status == 1
      = link_to item_purchase_index_path(@item), class: "item-details__buy-btn" do
        購入画面に進む
    -else
      .item-details__buy-btn
        この商品は、出品が停止されています

    .item-details__text
      .item-details__text__inner
        = simple_format(@item.text)

    .item-details__btn
      .item-details__btn__left
        = link_to '#', class: 'item-details__btn__left__1' do
          = icon 'far', 'heart', class: 'item-details__btn__left__1__font, item-details__btn__left__1__icon'
          %span.item-details__btn__left__1__font.item-details__btn__left__1__text いいね!
          %span.item-details__btn__left__1__font 0

        = link_to '#', class: 'item-details__btn__left__2' do
          = icon 'far', 'flag', class: 'item-details__btn__left__2__font, item-details__btn__left__2__icon'
          %span.item-details__btn__left__2__font 不適切な商品の報告

      .item-details__btn__right
        = link_to '#' do
          = icon 'fas', 'lock', class: 'item-details__btn__right__font, item-details__btn__right__icon'
          %span.item-details__btn__right__font あんしん・あんぜんへの取り組み

  .item-message
    .item-message__container
      .item-message__content
        %p.item-message__content__attention 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea{type: 'text', class: 'item-message__content__textarea'} 
        %input{type: 'submit', value: 'コメントする', class: 'item-message__content__submit'}

  %ul.item-link-nav
    %li.item-link-nav__prev
      = link_to '#' do
        = icon 'fas', 'chevron-left', class: 'item-link-nav__prev__font, item-link-nav__prev__icon'
        %span.item-link-nav__prev__font 前の商品
    %li.item-link-nav__next
      = link_to '#' do
        %span.item-link-nav__next__font 次の商品
        = icon 'fas', 'chevron-right', class: 'item-link-nav__next__font, item-link-nav__next__icon'

  .item-link-sns
    .item-link-sns__box
      %ul.item-link-sns__list
        %li
          = link_to '#' do
            = icon 'fab', 'facebook-square', class: 'item-link-sns__icon, item-link-sns__icon--facebook'
        %li
          = link_to '#' do
            =icon 'fab', 'twitter-square', class: 'item-link-sns__icon, item-link-sns__icon--twitter'
        %li
          = link_to '#' do
            = icon 'fab', 'pinterest-square', class: 'item-link-sns__icon, item-link-sns__icon--pinterest'

  .another-items
    %h2.another-items__head
      = link_to '#', class: 'another-items__head__title' do
        = @user.nickname
        %span さんのその他の出品
    .another-items__content
      - @items.each do |item|
        .another-items__content__box
          = link_to item_path(item) do
            .another-items__content__box__image
              %figure#other_img
                - item.images.each do |image|
                  = image_tag "#{image.image_url}", size: "220x220"
            .another-items__content__box__text
              %h3.another-items__name
                = item.name
              .another-items__info
                .another-items__info__price
                  = converting_to_jpy(item.price)
                .another-items__info__like
                  = icon 'far', 'heart', class: 'another-items__info__like__icon'
                  %span.another-items__info__like__num 0

  .item-bottom-nav
    %ul.item-bottom-nav__box
      %li
        = link_to root_path, class: 'item-bottom-nav__top-path' do
          エフマケ
        = icon 'fas', 'chevron-right', class: 'item-bottom-nav__icon'

      %li.item-bottom-nav__link
        %span 
          = @item.name