config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: 'items#index'

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :cards

  resources :items do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    member do
      get "change0", to: 'items#change0'
      get "change1", to: 'items#change1'
    end
  end
  
  resources :users do
    member do
      get "profile"
      get "logout"
      get "info"
      get "pageedit"
    end
  end

  get '/registration', to: 'items#registration'
  get '/card', to: 'items#card'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, required: true
  validates :user_id, presence: true
  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  
  require 'payjp'
  before_action :set_card

  def new
    card = Card.where(user_id: current_user.id).first
    redirect_to action: "index" if card.present?
  end

  def create #PayjpとCardのデータベース作成の実施
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: 'test',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new( user_id: current_user.id, 
                        customer_id: customer.id,
                        card_id: customer.default_card
                      )
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  def delete #PayjpとCardのデータベースを削除
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "new"
  end

  def show #CardデータをPayjpに送り、情報を引き出す
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  require 'payjp'
  before_action :set_card

  def index
  end

  def new
  end

  def create #PayjpとCardのデータベース作成の実施
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: 'test',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new( user_id: current_user.id, 
                        customer_id: customer.id,
                        card_id: customer.default_card
                      )
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  def delete #PayjpとCardのデータベースを削除
    if card.blank?
      redirect_to action: "create"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      redirect_to action: "new"
    end
  end

  def show #CardデータをPayjpに送り、情報を引き出す
    if card.blank?
      redirect_to action: "new"
    else  
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private

  def set_card
    card = Card.where(user_id: current_user.id).first
  end
end

app/views/cards/card.html.haml
-# - breadcrumb :card
-# .bread
-#   .bread__name
-#     = breadcrumbs 
.mypage
  .mypage__container
    = render partial: 'myside'
    .mypage__container__main-card
      .mypage__container__main-card__h2
        支払い方法
      .mypage__container__main-card__form
        .mypage__container__main-card__form__title
          クレジットカード一覧
        = link_to '', class: "hoge" do
          %button.btn.btn-lg.btn-default{id:"card_btn"} 
            %i.far.fa-credit-card
            クレジットカードを追加する
      = link_to '', class: "hoge" do
        .mypage__container__main-card__payment
          支払い方法について
          %i.fas.fa-angle-right

app/views/cards/index.html.haml
- breadcrumb :cards
.bread
  .bread__name
    = breadcrumbs 
.mypage
  .mypage__container
    = render partial: 'items/myside'
    .mypage__container__main-card
      .mypage__container__main-card__h2
        支払い方法
      .mypage__container__main-card__form
        .mypage__container__main-card__form__title
          クレジットカード一覧
        = link_to new_card_path, class: "hoge" do
          %button.btn.btn-lg.btn-default{id:"card_btn"} 
            %i.far.fa-credit-card
            クレジットカードを追加する
      = link_to '', class: "hoge" do
        .mypage__container__main-card__payment
          支払い方法について
          %i.fas.fa-angle-right

app/views/cards/new.html.haml
- breadcrumb :new_card
.bread
  .bread__name
    = breadcrumbs 
.mypage
  .mypage__container
    = render partial: 'items/myside'
    .single_container-input
      .session-credit__main
        .session-credit__main__container
          %h2.session-credit__main__container__title クレジットカード情報入力
          = form_with url: signup_index_path, name: "charge-form", id: 'charge-form', method: :post, html:{class: 'session__main__container__box'} do |f|
            .session-credit__main__container__formGroup
              %label{for: "nickname"}
                カード番号
                %span.form__require 必須
              = f.text_field "number", class: "input__default", placeholder: "半角数字のみ", type: "text", id: "card_number", maxlength: "16"
              .session-credit__main__container__formGroup__sub
                %i.fab.fa-cc-visa
                %i.fab.fa-cc-mastercard
                %i.fab.fa-cc-jcb
                %i.fab.fa-cc-discover
                %i.fab.fa-cc-amex
                / ↑画像使うと容量圧迫するのでアイコンで仮置き
            .session-credit__main__container__formGroup
              %label{for: "nickname"}
                有効期限
                %span.form__require 必須
              .session-credit__main__container__formGroup__sub
                %select.select__wap#exp_month{name: "exp_month", type: "text"}
                  %option{value: "01"} 01
                  %option{value: "02"} 02
                  %option{value: "03"} 03
                  %option{value: "04"} 04
                  %option{value: "05"} 05
                  %option{value: "06"} 06
                  %option{value: "07"} 07
                  %option{value: "08"} 08
                  %option{value: "09"} 09
                  %option{value: "10"} 10
                  %option{value: "11"} 11
                  %option{value: "12"} 12
                %i.fas.fa-chevron-down.select_arrow
                %p 月
                %select.select__wap#exp_year{name: "exp_year", type: "text"}           
                  %option{value: "2019"} 19
                  %option{value: "2020"} 20
                  %option{value: "2021"} 21
                  %option{value: "2022"} 22
                  %option{value: "2023"} 23
                  %option{value: "2024"} 24
                  %option{value: "2025"} 25
                %i.fas.fa-chevron-down.select_arrow
                %p 年
              .session-credit__main__container__formGroup
                %label{for: "nickname"}
                  セキュリティーコード
                  %span.form__require 必須
                = f.text_field "cvc", class: "input__default cvc", placeholder: "カード背面4桁もしくは3桁の番号", type: "text"
                .session-credit__main__container__formGroup__link
                  = link_to root_path do
                    %i.fas.fa-question-circle
                    %p カード裏面の番号とは？
                .session-credit__main__container__formGroup#card_token
                  = f.submit "追加する", class: "btn_default btn_mail", id: "token_submit"