config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: 'items#index'

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :cards

  resources :items do
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    member do
      get "change0", to: 'items#change0'
      get "change1", to: 'items#change1'
    end
  end
  
  resources :users do
    member do
      get "profile"
      get "logout"
      get "info"
      get "pageedit"
    end
  end

  get '/registration', to: 'items#registration'
  get '/card', to: 'items#card'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :comments ,dependent: :destroy
  has_many :images ,dependent: :destroy
  belongs_to :user,optional: true
  has_one :order
  belongs_to_active_hash :prefecture
  accepts_nested_attributes_for :images

  validates :name, :text, :condition, :fee_burden, :service, :prefecture_id, :handing_time, :price, presence: true
  #画像がない場合のバリデーション
  validate :require_any_image
  def require_any_image
    errors.add(:base, :no_image) if images.blank?
  end

  enum condition: {'新品未使用': 1, '未使用に近い': 2, '目立った傷や汚れなし': 3, '傷や汚れあり': 4, '全体的に状態が悪い': 5}
  enum fee_burden: {'送料込み（出品者負担）': 1, '着払い（購入者負担）': 2}
  enum service: {'未定': 1, 'らくらくメルカリ便': 2, 'ゆうメール': 3, 'レターパック': 4, '普通郵便（定形、定形外）': 5, 'クロネコヤマト': 6, 'ゆうパック': 7, 'クリックポスト': 8, 'ゆうパケット': 9}
  enum handing_time: {'１〜２日で発送': 1, '２〜３日で発送': 2, '４〜７日で発送': 3}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  before_action :set_user 

  def index
    @items = Item.all.where.not(trading_status: 2)
  end
  
  def new
    @item = Item.new
    @item.images.build
    render layout: 'devise'
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.build
      redirect_to new_item_path
    end
  end
  
  def show
    @user = User.find(@item[:seller_user_id])
    @items = Item.where(seller_user_id: @user[:id]).where.not(id: params[:id]).where.not(trading_status: 2)
    @images = @item.images
    render layout: 'items_show'
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render item_path
    end
  end

  def edit
    render layout: 'devise'
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path(@item)
    end
  end

  def change0
    @item = Item.find(params[:id])
    @item.update_attribute(:trading_status, "0")
    redirect_to item_path
  end

  def change1
    @item = Item.find(params[:id])
    @item.update_attribute(:trading_status, "1")
    redirect_to item_path
  end

  private
  def item_params
    params.require(:item).permit(:name,:text,:condition,:fee_burden,:service,:prefecture_id,:handing_time,:price,:trading_status,:service,:category_id, 
    images_attributes:[:image_url, :_destroy, :id]).merge(seller_user_id:current_user.id)
  end

  # def image_params
    #imageのストロングパラメータの設定.js側でimagesをrequireすれば画像のみを引き出せるように設定する。
    # params.require(:images).permit({:images => []})
  # end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_user
    @user = User.where(id: current_user.id).first if user_signed_in?
  end

end

app/views/items/mypage/_icon.html.haml
= link_to profile_user_path do
  .wrapping
    .myicon
      .myicon__img
        - if @user.icon?
          = image_tag "#{user.icon}", size: "50x50", id: "my_icon"
        - else
          = image_tag "/myicon.png", size: "50x50", id: "my_icon"
      .myicon__name
        = @user.nickname
      .myicon__number
        評価  0   出品数  0

app/views/items/mypage/_news.html.haml
= link_to "#" do
  .mypage__list
    .mypage__list__icon
      = image_tag "/logo_red.svg", size: "36x36"
    .mypage__list__text
      .mypage__list__text__title
        事務局から個別メッセージ「ログイン通知」
      .mypage__list__text__time
        %i.far.fa-clock
        ２時間前
    .mypage__list__mark
      %i.fas.fa-chevron-right

app/views/items/mypage/_todo.html.haml
.mypage__none
  .mypage__none__image
    = image_tag "/logo_gray.svg", size: "150x150"
  .mypage__none__text
    現在、やることリストはありません

app/views/items/mypage/_trading.html.haml
.mypage__none
  .mypage__none__image
    = image_tag "/logo_gray.svg", size: "150x150"
  .mypage__none__text
    取引中の商品がありません

app/views/items/mypage/_transaction.html.haml
.mypage__none
  .mypage__none__image
    = image_tag "/logo_gray.svg", size: "150x150"
  .mypage__none__text
    過去に取引した商品がありません